### ISSUE TITLE
Update download URL to 0.5

### ISSUE THREAD

**Issue by davidanthoff** [staticfloat/status.julialang.org#25]
Could this URL http://status.julialang.org/stable/win64 and http://status.julialang.org/stable/win32 be updated to point to the 0.5 release?

**Comment by staticfloat** [comment]
Done.  Although note that this isn't the recommended way to get the latest stable builds anymore, we've got a more foolproof method using just AWS naming.  See how Travis [downloads the latest Julia](https://github.com/travis-ci/travis-build/blob/f9c59bf4af125e91314586b0a4fca28cf3d7173c/lib/travis/build/script/julia.rb#L102-L110) for instance.  Although it's true that this doesn't give you the latest `stable` release without regard for version number, you probably shouldn't blindly upgrade from 0.4 to 0.5 automatically anyway, since there are deprecations and whatnot that you will have to deal with.

**Comment by davidanthoff** [comment]
Thanks. I have a PowerShell command ``update-julia`` that installs the latest julia version automatically using that link. That is not an auto-update, and this link is really helpful for that.

**Comment by staticfloat** [comment]
Well, I'm glad that someone finds this website useful!
